# Generated by Django 5.0.6 on 2024-06-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0011_alter_inputtype_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltemplate',
            name='tool_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tooltemplate',
            name='tool_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tooltemplate',
            name='tool_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_tool_type', to='swift.tooltype'),
        ),
        migrations.AlterField(
            model_name='tooltemplate',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
