# Generated by Django 5.0.6 on 2024-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_keyword_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='price',
        ),
        migrations.AddField(
            model_name='variants',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
