# Generated by Django 5.0.6 on 2024-06-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_product_price_remove_variants_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='title',
            new_name='variant_name',
        ),
        migrations.AddField(
            model_name='variants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
